#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Role-Basic
Version  : 0.13
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/O/OV/OVID/Role-Basic-0.13.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/O/OV/OVID/Role-Basic-0.13.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libr/librole-basic-perl/librole-basic-perl_0.13-2.debian.tar.xz
Summary  : 'Just roles. Nothing else.'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-Role-Basic-license
Requires: perl-Role-Basic-man

%description
Role-Basic
INSTALLATION
To install this module, run the following commands:
perl Build.PL
./Build
./Build test
./Build install

%package license
Summary: license components for the perl-Role-Basic package.
Group: Default

%description license
license components for the perl-Role-Basic package.


%package man
Summary: man components for the perl-Role-Basic package.
Group: Default

%description man
man components for the perl-Role-Basic package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n Role-Basic-0.13
mkdir -p %{_topdir}/BUILD/Role-Basic-0.13/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/Role-Basic-0.13/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-Role-Basic
cp deblicense/copyright %{buildroot}/usr/share/doc/perl-Role-Basic/deblicense_copyright
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/Role/Basic.pm
/usr/lib/perl5/site_perl/5.26.1/Role/Basic/Philosophy.pod

%files license
%defattr(-,root,root,-)
/usr/share/doc/perl-Role-Basic/deblicense_copyright

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/Role::Basic.3
/usr/share/man/man3/Role::Basic::Philosophy.3
